name: Publish to Docker Hub
description: |
  This workflow publishes the Docker image to Docker Hub.

on:
  push:
    branches:
      - master
      - develop

permissions:
  security-events: write
  actions: read
  contents: read

jobs:
  analyze_code:
    name: Analyze
    uses: cabrera-evil/workflows/.github/workflows/code-analysis.yaml@master
    with:
      default_branch: ${{ github.event.repository.default_branch }}
      push_before_sha: ${{ github.event.before }}
      push_base_sha: ${{ github.event.base_ref }}
    secrets: inherit

  publish:
    name: Publish
    needs: analyze_code
    uses: cabrera-evil/workflows/.github/workflows/publish-docker.yaml@master
    with:
      docker_image: ${{ github.event.repository.name }}
    secrets: inherit
